### ISSUE TITLE
Issue with using pip install on Windows

### ISSUE THREAD

**Issue by vaisest** [yanorestes/crypyto#1]
```
PS C:\Users\Turtvaiz> pip install crypyto
Collecting crypyto
  Using cached https://files.pythonhosted.org/packages/47/d7/a2843f5dfc2264bcd88765467cf5efc07469b9d4b47bda72f2fc4b52b275/crypyto-0.3.0.tar.gz
Requirement already satisfied: unidecode in c:\users\turtvaiz\appdata\local\programs\python\python37\lib\site-packages (from crypyto) (1.0.23)
Requirement already satisfied: Pillow in c:\users\turtvaiz\appdata\local\programs\python\python37\lib\site-packages (from crypyto) (5.3.0)
Installing collected packages: crypyto
  Running setup.py install for crypyto ... error
    Complete output from command c:\users\turtvaiz\appdata\local\programs\python\python37\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Turtvaiz\\AppData\\Local\\Temp\\pip-install-56tm90ld\\crypyto\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Turtvaiz\AppData\Local\Temp\pip-record-1cj8i6k6\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib
    creating build\lib\crypyto
    copying crypyto\ciphers.py -> build\lib\crypyto
    copying crypyto\substitution_alphabets.py -> build\lib\crypyto
    copying crypyto\__init__.py -> build\lib\crypyto
    creating build\lib\crypyto\static
    creating build\lib\crypyto\static\Betamaze
    copying crypyto\static\Betamaze\0.png -> build\lib\crypyto\static\Betamaze
    copying crypyto\static\Betamaze\1.png -> build\lib\crypyto\static\Betamaze
    copying crypyto\static\Betamaze\2.png -> build\lib\crypyto\static\Betamaze
    copying crypyto\static\Betamaze\3.png -> build\lib\crypyto\static\Betamaze
    copying crypyto\static\Betamaze\4.png -> build\lib\crypyto\static\Betamaze
    copying crypyto\static\Betamaze\5.png -> build\lib\crypyto\static\Betamaze
    copying crypyto\static\Betamaze\6.png -> build\lib\crypyto\static\Betamaze
    copying crypyto\static\Betamaze\7.png -> build\lib\crypyto\static\Betamaze
    copying crypyto\static\Betamaze\8.png -> build\lib\crypyto\static\Betamaze
    copying crypyto\static\Betamaze\9.png -> build\lib\crypyto\static\Betamaze
    copying crypyto\static\Betamaze\A.png -> build\lib\crypyto\static\Betamaze
    copying crypyto\static\Betamaze\B.png -> build\lib\crypyto\static\Betamaze
    copying crypyto\static\Betamaze\C.png -> build\lib\crypyto\static\Betamaze
    copying crypyto\static\Betamaze\colon.png -> build\lib\crypyto\static\Betamaze
    copying crypyto\static\Betamaze\comma.png -> build\lib\crypyto\static\Betamaze
    copying crypyto\static\Betamaze\D.png -> build\lib\crypyto\static\Betamaze
    copying crypyto\static\Betamaze\E.png -> build\lib\crypyto\static\Betamaze
    copying crypyto\static\Betamaze\F.png -> build\lib\crypyto\static\Betamaze
    copying crypyto\static\Betamaze\G.png -> build\lib\crypyto\static\Betamaze
    copying crypyto\static\Betamaze\H.png -> build\lib\crypyto\static\Betamaze
    copying crypyto\static\Betamaze\I.png -> build\lib\crypyto\static\Betamaze
    copying crypyto\static\Betamaze\J.png -> build\lib\crypyto\static\Betamaze
    copying crypyto\static\Betamaze\K.png -> build\lib\crypyto\static\Betamaze
    copying crypyto\static\Betamaze\L.png -> build\lib\crypyto\static\Betamaze
    copying crypyto\static\Betamaze\M.png -> build\lib\crypyto\static\Betamaze
    copying crypyto\static\Betamaze\N.png -> build\lib\crypyto\static\Betamaze
    copying crypyto\static\Betamaze\O.png -> build\lib\crypyto\static\Betamaze
    copying crypyto\static\Betamaze\P.png -> build\lib\crypyto\static\Betamaze
    copying crypyto\static\Betamaze\parenthesis.png -> build\lib\crypyto\static\Betamaze
    copying crypyto\static\Betamaze\period.png -> build\lib\crypyto\static\Betamaze
    copying crypyto\static\Betamaze\Q.png -> build\lib\crypyto\static\Betamaze
    copying crypyto\static\Betamaze\quote.png -> build\lib\crypyto\static\Betamaze
    copying crypyto\static\Betamaze\R.png -> build\lib\crypyto\static\Betamaze
    copying crypyto\static\Betamaze\S.png -> build\lib\crypyto\static\Betamaze
    copying crypyto\static\Betamaze\semicolon.png -> build\lib\crypyto\static\Betamaze
    copying crypyto\static\Betamaze\space.png -> build\lib\crypyto\static\Betamaze
    copying crypyto\static\Betamaze\T.png -> build\lib\crypyto\static\Betamaze
    copying crypyto\static\Betamaze\U.png -> build\lib\crypyto\static\Betamaze
    copying crypyto\static\Betamaze\V.png -> build\lib\crypyto\static\Betamaze
    copying crypyto\static\Betamaze\W.png -> build\lib\crypyto\static\Betamaze
    copying crypyto\static\Betamaze\X.png -> build\lib\crypyto\static\Betamaze
    copying crypyto\static\Betamaze\Y.png -> build\lib\crypyto\static\Betamaze
    copying crypyto\static\Betamaze\Z.png -> build\lib\crypyto\static\Betamaze
    creating build\lib\crypyto\static\Pigpen
    copying crypyto\static\Pigpen\A.png -> build\lib\crypyto\static\Pigpen
    copying crypyto\static\Pigpen\B.png -> build\lib\crypyto\static\Pigpen
    copying crypyto\static\Pigpen\C.png -> build\lib\crypyto\static\Pigpen
    copying crypyto\static\Pigpen\D.png -> build\lib\crypyto\static\Pigpen
    copying crypyto\static\Pigpen\E.png -> build\lib\crypyto\static\Pigpen
    copying crypyto\static\Pigpen\F.png -> build\lib\crypyto\static\Pigpen
    copying crypyto\static\Pigpen\G.png -> build\lib\crypyto\static\Pigpen
    copying crypyto\static\Pigpen\H.png -> build\lib\crypyto\static\Pigpen
    copying crypyto\static\Pigpen\I.png -> build\lib\crypyto\static\Pigpen
    copying crypyto\static\Pigpen\J.png -> build\lib\crypyto\static\Pigpen
    copying crypyto\static\Pigpen\K.png -> build\lib\crypyto\static\Pigpen
    copying crypyto\static\Pigpen\L.png -> build\lib\crypyto\static\Pigpen
    copying crypyto\static\Pigpen\M.png -> build\lib\crypyto\static\Pigpen
    copying crypyto\static\Pigpen\N.png -> build\lib\crypyto\static\Pigpen
    copying crypyto\static\Pigpen\O.png -> build\lib\crypyto\static\Pigpen
    copying crypyto\static\Pigpen\P.png -> build\lib\crypyto\static\Pigpen
    copying crypyto\static\Pigpen\Q.png -> build\lib\crypyto\static\Pigpen
    copying crypyto\static\Pigpen\R.png -> build\lib\crypyto\static\Pigpen
    copying crypyto\static\Pigpen\S.png -> build\lib\crypyto\static\Pigpen
    copying crypyto\static\Pigpen\T.png -> build\lib\crypyto\static\Pigpen
    copying crypyto\static\Pigpen\U.png -> build\lib\crypyto\static\Pigpen
    copying crypyto\static\Pigpen\V.png -> build\lib\crypyto\static\Pigpen
    copying crypyto\static\Pigpen\W.png -> build\lib\crypyto\static\Pigpen
    copying crypyto\static\Pigpen\X.png -> build\lib\crypyto\static\Pigpen
    copying crypyto\static\Pigpen\Y.png -> build\lib\crypyto\static\Pigpen
    copying crypyto\static\Pigpen\Z.png -> build\lib\crypyto\static\Pigpen
    creating build\lib\crypyto\static\Templar
    copying crypyto\static\Templar\A.png -> build\lib\crypyto\static\Templar
    copying crypyto\static\Templar\B.png -> build\lib\crypyto\static\Templar
    copying crypyto\static\Templar\C.png -> build\lib\crypyto\static\Templar
    copying crypyto\static\Templar\D.png -> build\lib\crypyto\static\Templar
    copying crypyto\static\Templar\E.png -> build\lib\crypyto\static\Templar
    copying crypyto\static\Templar\F.png -> build\lib\crypyto\static\Templar
    copying crypyto\static\Templar\G.png -> build\lib\crypyto\static\Templar
    copying crypyto\static\Templar\H.png -> build\lib\crypyto\static\Templar
    copying crypyto\static\Templar\I.png -> build\lib\crypyto\static\Templar
    copying crypyto\static\Templar\J.png -> build\lib\crypyto\static\Templar
    copying crypyto\static\Templar\K.png -> build\lib\crypyto\static\Templar
    copying crypyto\static\Templar\L.png -> build\lib\crypyto\static\Templar
    copying crypyto\static\Templar\M.png -> build\lib\crypyto\static\Templar
    copying crypyto\static\Templar\N.png -> build\lib\crypyto\static\Templar
    copying crypyto\static\Templar\O.png -> build\lib\crypyto\static\Templar
    copying crypyto\static\Templar\P.png -> build\lib\crypyto\static\Templar
    copying crypyto\static\Templar\Q.png -> build\lib\crypyto\static\Templar
    copying crypyto\static\Templar\R.png -> build\lib\crypyto\static\Templar
    copying crypyto\static\Templar\S.png -> build\lib\crypyto\static\Templar
    copying crypyto\static\Templar\T.png -> build\lib\crypyto\static\Templar
    copying crypyto\static\Templar\U.png -> build\lib\crypyto\static\Templar
    copying crypyto\static\Templar\V.png -> build\lib\crypyto\static\Templar
    copying crypyto\static\Templar\W.png -> build\lib\crypyto\static\Templar
    copying crypyto\static\Templar\X.png -> build\lib\crypyto\static\Templar
    copying crypyto\static\Templar\Y.png -> build\lib\crypyto\static\Templar
    copying crypyto\static\Templar\Z.png -> build\lib\crypyto\static\Templar
    running install_lib
    running install_data
    running install_egg_info
    running egg_info
    writing crypyto.egg-info\PKG-INFO
    writing dependency_links to crypyto.egg-info\dependency_links.txt
    writing requirements to crypyto.egg-info\requires.txt
    writing top-level names to crypyto.egg-info\top_level.txt
    reading manifest file 'crypyto.egg-info\SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Turtvaiz\AppData\Local\Temp\pip-install-56tm90ld\crypyto\setup.py", line 49, in <module>
        'Pillow',
      File "c:\users\turtvaiz\appdata\local\programs\python\python37\lib\site-packages\setuptools\__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\turtvaiz\appdata\local\programs\python\python37\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\turtvaiz\appdata\local\programs\python\python37\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\users\turtvaiz\appdata\local\programs\python\python37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\turtvaiz\appdata\local\programs\python\python37\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\turtvaiz\appdata\local\programs\python\python37\lib\distutils\command\install.py", line 557, in run
        self.run_command(cmd_name)
      File "c:\users\turtvaiz\appdata\local\programs\python\python37\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\turtvaiz\appdata\local\programs\python\python37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\turtvaiz\appdata\local\programs\python\python37\lib\site-packages\setuptools\command\install_egg_info.py", line 34, in run
        self.run_command('egg_info')
      File "c:\users\turtvaiz\appdata\local\programs\python\python37\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\turtvaiz\appdata\local\programs\python\python37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\turtvaiz\appdata\local\programs\python\python37\lib\site-packages\setuptools\command\egg_info.py", line 278, in run
        self.find_sources()
      File "c:\users\turtvaiz\appdata\local\programs\python\python37\lib\site-packages\setuptools\command\egg_info.py", line 293, in find_sources
        mm.run()
      File "c:\users\turtvaiz\appdata\local\programs\python\python37\lib\site-packages\setuptools\command\egg_info.py", line 524, in run
        self.add_defaults()
      File "c:\users\turtvaiz\appdata\local\programs\python\python37\lib\site-packages\setuptools\command\egg_info.py", line 567, in add_defaults
        self.read_manifest()
      File "c:\users\turtvaiz\appdata\local\programs\python\python37\lib\site-packages\setuptools\command\sdist.py", line 199, in read_manifest
        self.filelist.append(line)
      File "c:\users\turtvaiz\appdata\local\programs\python\python37\lib\site-packages\setuptools\command\egg_info.py", line 466, in append
        path = convert_path(item)
      File "c:\users\turtvaiz\appdata\local\programs\python\python37\lib\distutils\util.py", line 110, in convert_path
        raise ValueError("path '%s' cannot be absolute" % pathname)
    ValueError: path '/home/yan/crypyto/crypyto/static/Betamaze/0.png' cannot be absolute

    ----------------------------------------
Command "c:\users\turtvaiz\appdata\local\programs\python\python37\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Turtvaiz\\AppData\\Local\\Temp\\pip-install-56tm90ld\\crypyto\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Turtvaiz\AppData\Local\Temp\pip-record-1cj8i6k6\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Turtvaiz\AppData\Local\Temp\pip-install-56tm90ld\crypyto\
```

**Comment by yyyyyyyan** [comment]
Sorry I'm late. Thanks for this issue! I'm going to investigate and this will soon be fixed.
